services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/kgodisoleonard/agritech-db:latest
    container_name: agritech_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: agritech
      POSTGRES_USER: agritech_user
      POSTGRES_PASSWORD: change_me
    ports:
      - "5432:5432"
    volumes:
      - agritech_data:/var/lib/postgresql/data

volumes:
  agritech_data:
