-- ============================================================
-- Sample seed data (optional) — run after schema.sql
-- All ids are now string UUIDs generated by gen_random_uuid(),
-- so related rows are looked up by their unique name instead of
-- a hardcoded integer id.
-- ============================================================

INSERT INTO farmers (name, location, contact) VALUES
('Thabo Mokoena', 'Polokwane', '082 111 2233'),
('Nomvula Dlamini', 'Tzaneen', '083 444 5566');

INSERT INTO suppliers (name, location, contact) VALUES
('Limpopo Agri Supplies', 'Polokwane', '015 123 4567'),
('GreenGro Fertilizers', 'Nelspruit', '013 987 6543');

INSERT INTO supplier_products (supplier_id, product_name, price)
SELECT id, 'Maize Seed 10kg', 450.00 FROM suppliers WHERE name = 'Limpopo Agri Supplies'
UNION ALL
SELECT id, 'NPK Fertilizer 50kg', 620.00 FROM suppliers WHERE name = 'Limpopo Agri Supplies'
UNION ALL
SELECT id, 'Organic Compost 25kg', 210.00 FROM suppliers WHERE name = 'GreenGro Fertilizers';

INSERT INTO expenses (farmer_id, item, category, amount, date)
SELECT id, 'Maize Seed 10kg', 'seeds', 450.00, CURRENT_DATE FROM farmers WHERE name = 'Thabo Mokoena'
UNION ALL
SELECT id, 'Organic Compost 25kg', 'fertilizer', 210.00, CURRENT_DATE FROM farmers WHERE name = 'Nomvula Dlamini';

INSERT INTO income (farmer_id, item, amount, date)
SELECT id, 'Maize sale - local market', 3200.00, CURRENT_DATE FROM farmers WHERE name = 'Thabo Mokoena'
UNION ALL
SELECT id, 'Vegetable sale', 1500.00, CURRENT_DATE FROM farmers WHERE name = 'Nomvula Dlamini';

INSERT INTO group_orders (product_id, supplier_id, status, target_quantity, current_quantity, discount_rate)
SELECT sp.id, sp.supplier_id, 'open', 20, 8, 10.00
FROM supplier_products sp
WHERE sp.product_name = 'NPK Fertilizer 50kg';

INSERT INTO group_order_items (group_order_id, farmer_id, quantity, total_price, status, joined_at)
SELECT go.id, f.id, 5, 2790.00, 'confirmed', NOW()
FROM group_orders go
JOIN supplier_products sp ON sp.id = go.product_id
JOIN farmers f ON f.name = 'Thabo Mokoena'
WHERE sp.product_name = 'NPK Fertilizer 50kg'
UNION ALL
SELECT go.id, f.id, 3, 1674.00, 'pending', NOW()
FROM group_orders go
JOIN supplier_products sp ON sp.id = go.product_id
JOIN farmers f ON f.name = 'Nomvula Dlamini'
WHERE sp.product_name = 'NPK Fertilizer 50kg';

INSERT INTO notifications (supplier_id, group_order_id, message, is_read)
SELECT go.supplier_id, go.id, 'Your NPK Fertilizer 50kg group order reached 8/20 units.', FALSE
FROM group_orders go
JOIN supplier_products sp ON sp.id = go.product_id
WHERE sp.product_name = 'NPK Fertilizer 50kg';
