server.port=${PORT:8080}

azure.openai.endpoint=${AZURE_OPENAI_ENDPOINT:}
azure.openai.api-key=${AZURE_OPENAI_API_KEY:}
azure.openai.deployment=${AZURE_OPENAI_DEPLOYMENT:}

spring.application.name=agritech-spring-ai-service
